# fly.toml app configuration file generated for bagle-map on 2024-07-29T16:23:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bagle-map'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile.dev'
  [build.args]
    FLY_DEPLOY = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
