# fly.toml app configuration file generated for bagel-map on 2024-08-15T15:08:19+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bagel-map'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile.dev'
  [build.args]
    FLY_DEPLOY = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = 512

[deploy]
  release_command = './bin/rails db:prepare'
